# Generated by Django 4.1.7 on 2023-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameplaysession_delete_gameplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplaysession',
            name='total_game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
