# Generated by Django 4.1.7 on 2023-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameplaysession_total_game_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=500, unique=True)),
                ('faction_choice', models.CharField(max_length=100)),
            ],
        ),
    ]
