# Generated by Django 4.1.7 on 2023-03-16 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_whitelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelist',
            name='faction_choice',
        ),
        migrations.AddField(
            model_name='whitelist',
            name='twitter_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
