# Generated by Django 4.1.7 on 2023-03-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_whitelist_faction_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='faction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
